services:
  springboot:
    image: minishop
    container_name: minishop
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10002:10002"
    env_file:
      - .env
    networks:
      - project

networks:
  project:
    external: true