services:
  springboot:
    image: yt_codingapple_springbootweb
    container_name: yt_codingapple_springbootweb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10002:10002"
    env_file:
      - .env
    networks:
      - project

networks:
  project:
    external: true